// @vitest-environment jsdom

import { describe, expect, it } from "vitest";

import { CampaignRenderer } from "./renderer";

describe("CampaignRenderer stats contract", () => {
  it("keeps every published stats key stable", () => {
    const renderer = Object.assign(Object.create(CampaignRenderer.prototype), {
      passes: {
        shell: { stats: () => ({ width: 1, height: 1, device: "test", cameraContract: "test" }) },
        map: { stats: () => ({}) },
        clouds: { stats: () => ({ cloudQuads: 0 }) },
        fog: { stats: () => ({ fogEnabled: false, fogSources: 0 }) },
        territory: { stats: () => ({ pixels: 0 }) },
        lines: { stats: () => ({ segments: 0 }) },
        roads: { stats: () => ({ triangles: 0 }) },
        borders: { stats: () => ({ segments: 0 }) },
        markers: { stats: () => ({ markers: 0 }) },
        scenery: { stats: () => ({ scenery: 0 }) },
        standards: { stats: () => ({}) },
        selection: {
          stats: () => ({ selections: 0, garrisonedArmySelections: 0, maxSelectionRadius: 0 }),
        },
      },
      lastEntities: { cityEntities: 0, armyEntities: 0, cityEntityAnchors: [] },
      labelStats: {
        labels: 0,
        visibleLabels: 0,
        visibleLabelNames: [],
        visibleSeaLabelRects: [],
        visibleCityLabelRects: [],
        visibleArmyLabelRects: [],
        visibleFactionLabelRects: [],
        collisionCulls: 0,
        collisionCulledLabels: [],
        atlasWidth: 0,
        atlasHeight: 0,
        vertices: 0,
        layer: "raw-gpu-glyph-atlas",
      },
      lastCards: { rects: [], culls: [] },
      lastLabelComposition: { composedArmyCityLabels: 0 },
      lastFactionView: false,
      graphics: {},
      sceneryCandidates: [],
      mapDrawStats: null,
      framePerf: { buildMs: 0, uploadMs: 0, drawMs: 0, frameCpuMs: 0 },
    }) as CampaignRenderer;

    expect(Object.keys(renderer.stats())).toMatchInlineSnapshot(`
      [
        "renderer",
        "ready",
        "width",
        "height",
        "device",
        "cameraContract",
        "cityEntities",
        "armyEntities",
        "cityEntityAnchors",
        "labels",
        "visibleLabels",
        "visibleLabelNames",
        "visibleSeaLabelRects",
        "visibleCityLabelRects",
        "visibleArmyLabelRects",
        "visibleFactionLabelRects",
        "visibleCardRects",
        "labelCollisionCulls",
        "labelCollisionCulledLabels",
        "composedArmyCityLabels",
        "labelLayer",
        "labelAtlas",
        "labelVertices",
        "waterFeatures",
        "waterLayer",
        "mapSurface",
        "cloudQuads",
        "fogEnabled",
        "fogSources",
        "factionView",
        "graphics",
        "territoryPixels",
        "borderSegments",
        "mapMarkers",
        "cityMarkerRadiiPxByTier",
        "selections",
        "garrisonedArmySelections",
        "maxSelectionRadius",
        "standardStats",
        "scenery",
        "sceneryQuads",
        "sceneryStats",
        "sceneryCandidateStats",
        "lineSegments",
        "roadTriangles",
        "roadJunctionCaps",
        "seaLabelFits",
        "seaLabelFitZoom",
        "roadEdgesCulled",
        "roadWaterGaps",
        "seaLanes",
        "phases",
        "depth",
        "postCutoverScreenshots",
        "performance",
      ]
    `);
  });
});
