      let start=u32(inst1.y)*4u;
      let a=palette[start+u32(joints.x)];let b=palette[start+u32(joints.y)];
      let c=palette[start+u32(joints.z)];let d=palette[start+u32(joints.w)];
      let c0=a[0]*weights.x+b[0]*weights.y+c[0]*weights.z+d[0]*weights.w;
      let c1=a[1]*weights.x+b[1]*weights.y+c[1]*weights.z+d[1]*weights.w;
      let c2=a[2]*weights.x+b[2]*weights.y+c[2]*weights.z+d[2]*weights.w;
      let c3=a[3]*weights.x+b[3]*weights.y+c[3]*weights.z+d[3]*weights.w;
      let local=c0*position.x+c1*position.y+c2*position.z+c3;
      let n=normalize((c0*normal.x+c1*normal.y+c2*normal.z).xyz);
      let t=unitDirection((c0*tangent.x+c1*tangent.y+c2*tangent.z).xyz,vec3f(0));
      let angle=inst0.z-1.5707964;let co=cos(angle);let si=sin(angle);
      let p=local.xyz*inst1.x;
      let world=vec3f(inst0.x+p.x*co-p.y*si,inst0.y+p.x*si+p.y*co,p.z+inst2.x);
      let worldN=vec3f(n.x*co-n.y*si,n.x*si+n.y*co,n.z);
      let worldT=vec3f(t.x*co-t.y*si,t.x*si+t.y*co,t.z);
      let contact=mix(0.45,1.0,smoothstep(0.0,0.42,local.z));
      return VertexOut(projectWorld(world),world,worldN,worldT,uv,color.rgb,u32(material),factionMask,vec3f(inst0.w,inst2.z,mix(1.0,contact,1.0-inst2.z)),tangent.w,normalize((environment.worldToView*vec4f(worldN,0)).xyz));